import Head from 'next/head';

const Layout = ({ children }: {children: any}) => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/icon.jpg" />
      </Head>
      {children}
    </div>
  );
};

export default Layout;
